title: Hello, world! I'm Yu Yang!
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog, mainly to log down my Ph.D. learning path.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yu Yang # add your name
author-img: yuyang.jpg # add your photo
about-author: I am a Statistics Ph.D. student focusing on deep learning and Natural Language Processing. Always hungry to keep learning. # add description
social-twitter: YuYang97360922 # add your Twitter handle
social-facebook: 100024422318871 # add your Facebook handle
social-github: yuyang-yy # add your Github handle
social-linkedin: yuyang479614151 # add your Linkedin handle
social-email: yuyang_96@hotmail.com # add your Email address

# Tracker
analytics: UA-120124186-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Personal Settings
port: 5000
